/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FeedbackTypeService } from "../feedbackType.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FeedbackTypeCreateInput } from "./FeedbackTypeCreateInput";
import { FeedbackType } from "./FeedbackType";
import { FeedbackTypeFindManyArgs } from "./FeedbackTypeFindManyArgs";
import { FeedbackTypeWhereUniqueInput } from "./FeedbackTypeWhereUniqueInput";
import { FeedbackTypeUpdateInput } from "./FeedbackTypeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FeedbackTypeControllerBase {
  constructor(
    protected readonly service: FeedbackTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FeedbackType })
  @nestAccessControl.UseRoles({
    resource: "FeedbackType",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFeedbackType(
    @common.Body() data: FeedbackTypeCreateInput
  ): Promise<FeedbackType> {
    return await this.service.createFeedbackType({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        screenshot: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FeedbackType] })
  @ApiNestedQuery(FeedbackTypeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FeedbackType",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async feedbackTypes(@common.Req() request: Request): Promise<FeedbackType[]> {
    const args = plainToClass(FeedbackTypeFindManyArgs, request.query);
    return this.service.feedbackTypes({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        screenshot: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FeedbackType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FeedbackType",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async feedbackType(
    @common.Param() params: FeedbackTypeWhereUniqueInput
  ): Promise<FeedbackType | null> {
    const result = await this.service.feedbackType({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        screenshot: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FeedbackType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FeedbackType",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFeedbackType(
    @common.Param() params: FeedbackTypeWhereUniqueInput,
    @common.Body() data: FeedbackTypeUpdateInput
  ): Promise<FeedbackType | null> {
    try {
      return await this.service.updateFeedbackType({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          screenshot: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FeedbackType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FeedbackType",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFeedbackType(
    @common.Param() params: FeedbackTypeWhereUniqueInput
  ): Promise<FeedbackType | null> {
    try {
      return await this.service.deleteFeedbackType({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          screenshot: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
